---
ehagent_version: "0.1.0"
ehagent_binary_url: ""
ehagent_binary_local_path: ""
ehagent_binary_checksum: ""
ehagent_install_dir: /opt/ehagent
ehagent_user: ehagent
ehagent_group: ehagent
ehagent_panel_url: "wss://web.theflakito.com/ws/agent/"
ehagent_panel_target: "ehpanel-web"
ehagent_agent_type: "web"
ehagent_hostname: "{{ inventory_hostname }}"
ehagent_enrollment_token: "{{ vault_ehagent_enrollment_token }}"
ehagent_keypair_path: "/etc/ehagent/node.key"
ehagent_config_path: "/etc/ehagent/config.toml"
ehagent_log_level: "info"
ehagent_heartbeat_interval: 15
ehagent_telemetry_interval: 30
ehagent_validate_timeout: 60
ehagent_privileged_mode: false
