---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart ehpanel web
  ansible.builtin.systemd:
    name: "{{ ehpanel_web_panel_service_name }}"
    state: restarted
    enabled: true

- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
