---
# inventories/production/group_vars/web_nodes.yml

php_versions:
  - "8.1"
  - "8.2"
  - "8.3"
  - "8.4"

node_services_enabled:
  - nginx
  - httpd
  - lshttpd
  - mariadb
  - postgresql
  - valkey
  - pdns
  - postfix
  - dovecot
  - rspamd
  - vsftpd
  - ehpanel-web
  - ehagent-web

firewall_additional_ports:
  - "21/tcp"
  - "30000-30100/tcp"
