---
all:
  vars:
    inventory_environment: staging

  children:
    web_nodes:
      hosts:
        web-01.theflakito.com:
          ansible_host: 204.168.159.142

    radio_nodes:
      hosts: {}

    video_nodes:
      hosts: {}

    srt_nodes:
      hosts: {}

    all_managed_nodes:
      children:
        web_nodes:
        radio_nodes:
        video_nodes:
        srt_nodes:
