---
firewall_zone: public
firewall_allowed_services:
  - ssh
  - http
  - https
  - smtp
  - smtps
  - submission
  - imaps
  - pop3s
firewall_allowed_ports:
  - "53/tcp"
  - "53/udp"
firewall_blocked_ports:
  - "3306/tcp"
  - "5432/tcp"
  - "6379/tcp"
  - "8053/tcp"
  - "8080/tcp"
  - "11332/tcp"
  - "11333/tcp"
  - "11334/tcp"
firewall_additional_ports: []
firewall_rich_rules: []
firewall_strict_public_zone: true
firewall_disabled_services:
  - cockpit
  - dhcpv6-client
  - imap
  - pop3
  - mysql
  - postgresql
  - redis
