---
- name: reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
  when: not ansible_check_mode

- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
  when: not ansible_check_mode
