---
- name: restart postgresql
  ansible.builtin.systemd:
    name: "{{ postgresql_service_name }}"
    state: restarted

- name: reload postgresql
  ansible.builtin.systemd:
    name: "{{ postgresql_service_name }}"
    state: reloaded
